"""Allow NULL for check_in_time and check_out_time

Revision ID: 016baeab03ff
Revises: a3a35ccf5473
Create Date: 2024-10-18 15:55:14.273258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016baeab03ff'
down_revision = 'a3a35ccf5473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_log', schema=None) as batch_op:
        batch_op.alter_column('check_in_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_log', schema=None) as batch_op:
        batch_op.alter_column('check_in_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
