"""Add section field to Employee model

Revision ID: 136ef9424ffc
Revises: 228b70c31068
Create Date: 2024-09-30 22:45:24.690316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136ef9424ffc'
down_revision = '228b70c31068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
