"""Add monthly_work_time column

Revision ID: 1494e15e3ee7
Revises: 803c86c74ecb
Create Date: 2024-10-01 03:36:58.682237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1494e15e3ee7'
down_revision = '803c86c74ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_work_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('monthly_work_time')

    # ### end Alembic commands ###
