"""Create dashboard_user table

Revision ID: 157de1fa3492
Revises: 016baeab03ff
Create Date: 2024-10-18 18:01:57.808419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157de1fa3492'
down_revision = '016baeab03ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_user')
    # ### end Alembic commands ###
