"""Add check_in_time, check_out_time, daily_hours, monthly_hours to Employee

Revision ID: 1936dbd20fc8
Revises: 540b1d036f0e
Create Date: 2024-10-02 23:34:12.846757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1936dbd20fc8'
down_revision = '540b1d036f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('monthly_hours')
        batch_op.drop_column('daily_hours')

    # ### end Alembic commands ###
