"""Initial migration

Revision ID: 297ae56ca9f5
Revises: 28c99998ab0b
Create Date: 2024-11-17 08:51:03.582446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297ae56ca9f5'
down_revision = '28c99998ab0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
