"""Add MonthlyWorkTime table

Revision ID: 549abaaacf91
Revises: 1494e15e3ee7
Create Date: 2024-10-01 03:43:07.025598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549abaaacf91'
down_revision = '1494e15e3ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_work_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_work_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_work_time')
    # ### end Alembic commands ###
