"""Добавлено поле overtime в таблицу Employee

Revision ID: 6f1923d2f8ee
Revises: 297ae56ca9f5
Create Date: 2024-11-27 22:49:59.429125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1923d2f8ee'
down_revision = '297ae56ca9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('overtime', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'overtime')
    # ### end Alembic commands ###
