"""Added lunch start and end time to WorkLog

Revision ID: 7e80bcac760e
Revises: 28eb56d3e6b6
Create Date: 2024-10-03 00:54:21.865681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e80bcac760e'
down_revision = '28eb56d3e6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lunch_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lunch_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_log', schema=None) as batch_op:
        batch_op.drop_column('lunch_end_time')
        batch_op.drop_column('lunch_start_time')

    # ### end Alembic commands ###
