"""Add daily work time field

Revision ID: 803c86c74ecb
Revises: dc77ba49112d
Create Date: 2024-10-01 03:26:22.012642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803c86c74ecb'
down_revision = 'dc77ba49112d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_work_time', sa.Interval(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('daily_work_time')

    # ### end Alembic commands ###
