"""Add admin table

Revision ID: 86d5526ca190
Revises: b38734fad7a0
Create Date: 2024-10-04 19:01:27.682864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d5526ca190'
down_revision = 'b38734fad7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('current_shift')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_shift', sa.BOOLEAN(), nullable=True))

    op.drop_table('admin')
    # ### end Alembic commands ###
