"""Add lunch start and end times

Revision ID: 8b21861fc470
Revises: 7e80bcac760e
Create Date: 2024-10-03 01:17:37.959303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b21861fc470'
down_revision = '7e80bcac760e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lunch_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lunch_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('lunch_end_time')
        batch_op.drop_column('lunch_start_time')

    # ### end Alembic commands ###
