"""Add work start and end times

Revision ID: a3a35ccf5473
Revises: 1e9e800adb03
Create Date: 2024-10-17 01:57:12.924644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a35ccf5473'
down_revision = '1e9e800adb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('hours_per_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_per_week', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
