"""Add current_shift column to Employee model

Revision ID: b38734fad7a0
Revises: 8b21861fc470
Create Date: 2024-10-03 02:13:23.524268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38734fad7a0'
down_revision = '8b21861fc470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_shift', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('current_shift')

    # ### end Alembic commands ###
