"""Add check_in_date to Employee

Revision ID: d960cb6b0804
Revises: 549abaaacf91
Create Date: 2024-10-01 07:09:18.076024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd960cb6b0804'
down_revision = '549abaaacf91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('check_in_date')

    # ### end Alembic commands ###
