"""Add check-in and check-out fields

Revision ID: dc77ba49112d
Revises: 0260bee06729
Create Date: 2024-10-01 01:31:11.226339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc77ba49112d'
down_revision = '0260bee06729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('check_out', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in')

    # ### end Alembic commands ###
