"""Initial migration after reset

Revision ID: eb024b62f8c8
Revises: d960cb6b0804
Create Date: 2024-10-02 18:16:10.535940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb024b62f8c8'
down_revision = 'd960cb6b0804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_work_time')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('monthly_work_time')
        batch_op.drop_column('daily_work_time')
        batch_op.drop_column('check_in')
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('check_out', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('check_in', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('daily_work_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('monthly_work_time', sa.FLOAT(), nullable=True))
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('check_in_time')

    op.create_table('monthly_work_time',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.VARCHAR(length=7), nullable=False),
    sa.Column('total_work_time', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
